name: Commit Message Check

on:
  push:
    branches:
      - '*'
    # Exclude Dependabot from triggering the workflow
    paths-ignore:
      - 'dependabot/**'

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get commit range
      run: |
        if [[ -z "${{ github.event.before }}" ]]; then
          RANGE="${{ github.sha }}"
        else
          RANGE="${{ github.event.before }}..${{ github.sha }}"
        fi
        echo "Commit range: $RANGE"
        echo "::set-output name=commit_range::$RANGE"

    - name: Check commit messages
      run: |
        COMMIT_RANGE="${{ steps.get_commit_range.outputs.commit_range }}"
        COMMIT_MESSAGES=$(git log --pretty=format:"%s" $COMMIT_RANGE)

        # Loop through each commit message and check for Jira Issue Key pattern
        for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
          if [[ $COMMIT_MESSAGE =~ [A-Z]+-[0-9]+ ]]; then
            echo "Commit message is valid: $COMMIT_MESSAGE"
          else
            echo "Commit message is invalid: $COMMIT_MESSAGE"
            exit 1
          fi
        done
