name: Commit Message Check

on:
  push:
    branches:
      - '*'
    # Exclude Dependabot from triggering the workflow
    paths-ignore:
      - 'dependabot/**'

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit messages
      run: |
        # Get the list of commit messages in the current push
        if [[ -z "${{ github.event.before }}" ]]; then
          RANGE="HEAD"
        else
          RANGE="${{ github.event.before }}..${{ github.sha }}"
        fi
        COMMIT_MESSAGES=$(git log --pretty=format:"%s" $RANGE)

        # Loop through each commit message and check for Jira Issue Key pattern
        for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
          if [[ $COMMIT_MESSAGE =~ [A-Z]+-[0-9]+ ]]; then
            echo "Commit message is valid: $COMMIT_MESSAGE"
          else
            echo "Commit message is invalid: $COMMIT_MESSAGE"
            exit 1
          fi
        done
